food/urls.py
from django.urls import path
from . import views
app_name='food'
urlpatterns = [
    #food/hallo
    path('hallo/',views.index,name="index"),
    path('',views.ListClassViews.as_view(),name="list"),

    path('detail/<int:pk>',views.detail,name="detail"),
    #add item
    path('add/',views.CreateItemClassView.as_view(),name="add-item"),
    #edit
    path('edit/<int:pk>' ,views.UpdateItemClassView.as_view(),name="edit-item"),
    #delete
    path('delete/<int:pk>' ,views.DeleteItemClassView.as_view(),name="delete-item")
]

foodmenu/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('user/',include('users.urls')),

    path('register/',user_view.register,name="register"),
    path('login/',auth_view.LoginView.as_view(template_name='user/login.html'),name="login"),
    path('logout/',auth_view.LogoutView.as_view(template_name='user/logout.html'),name="logout"),
    path('profile/',user_view.profile,name="profile"),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path


app_name="user"
urlpatterns = [


]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desp = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://www.yanaya.co.zw/wp-content/uploads/2020/08/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.jpg")
    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.png")
    location = models.CharField(max_length=100)
    def __str__(self):
        return self.user.username

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .form import Itemform
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy

def index(request):
    return HttpResponse("Hello World")


# Item list
def list(request):
    item_list = Item.objects.all()
    # template=loader.get_template("food/index.html")
    
    context={
        'item_list':item_list

    }
    return render(request,'food/index.html',context=context)
    # return HttpResponse(template.render(context,request))

class ListClassViews(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'
    


# Show detail of item
def detail(request,pk):
    item_detail = Item.objects.get(pk=pk)
    context={
        'object':item_detail,
        'user':str(item_detail.user_name),
        'author':str(request.user.username)
    }
    
    
    return render(request,'food/detail.html',context=context)
    # return HttpResponse(f"this is item no {id}")

class DetailClassView(DetailView):
    model=Item
    template_name = 'food/detail.html'

# Create item 
def create_item(request):
    form = Itemform(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:list')
    context = {
        'form':form
    }
    return render(request,'food/add_item.html',context=context)

class CreateItemClassView(CreateView):
    model = Item
    form_class  =Itemform
    
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        
        return super().form_valid(form)
    template_name = 'food/add_item.html'

# Edit Item
def edit_item(request,id):
    item = Item.objects.get(id=id)

    form = Itemform(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:list')
    
    
    return render(request,'food/edit_item.html',context={"form":form})

class UpdateItemClassView(UpdateView):
    model = Item
    form_class  = Itemform
    template_name = 'food/edit_item.html'
    success_url ="/food/"

# Delete Item
def delete_item(request,id):
    item = Item.objects.get(id=id)
   
    if request.method   == 'POST' :

        item.delete()
    
        return redirect('food:list')
    return render(request,'food/delete_item.html',context={"item":item})

class DeleteItemClassView(DeleteView):
    model = Item
    template_name = 'food/delete_item.html'  
    success_url = '/food/'
    

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .form import RegisterForm
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        
        if form.is_valid():
            form.save()
            username =form.cleaned_data.get("username") 
            messages.success(request,f"welcome {username} your account is created")
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request,'user/register.html',context={"form":form})

@login_required
def profile(request):
    return render(request,'user/profile.html') 

food/templates/food/add_item.html
{% extends 'food/base.html' %}


{% block body %}
    <div class="container " style="height: 88vh; width: 100%;">
        <div class="row "style="height: 88vh; width: 100%; 
        display: flex;
        justify-content: center;
        ">
            <div class="" >
                <div class="card">
                    <div class="card-header bg-dark ">
                      <div class="card-title text-white">Add New Item</div>
                    </div>
                    <div class="card-body">
                        <form method="POST">

                        {% csrf_token %}
                        {%  for field in form %}
                           <div class="form-group" style="display: grid; grid-template-columns: 1fr 2fr;">
                            <label for="">{{field.name}}</label>
                            
                            {{field}}
                           </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-dark">Signup</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:list' %}" class="navbar-brand" > FoodApp</a>
         
        <div class="navbar">
          <a href="{% url 'food:add-item' %}" class="nav-item nav-link">Add Item</a>
          <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>

          {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
          {% else %}
          <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
          {% endif %}
          
          

    
        </div>
      
      </nav>
{% block body %}

{% endblock %}
      
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

food/templates/food/delete_item.html
<form action="" method="POST">
    {% csrf_token %}
    <h1>Are you sue you want to delete {{ item.item_name }} </h1>
   <button type="submit">confirm</button>
</form>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

{% if object %}

<div class="container">
    <div class="row justify-content-center align-items-center min-vh-100">
        <div class=" d-flex">
        <img class="col-md-8" src={{object.item_image}} alt="" height="400px" width="500px">
          <div class=" col-md-4 " style="display: flex; flex-direction: column; justify-content: center;">
           <h1>{{object.item_name}}</h1>
          <h2> ${{object.item_price}}</h2>
          <h3> {{object.item_desp}}</h3>
          <h6> {{is_author}}</h6>
          
        {% if user == author %}
          <a href="{% url 'food:edit-item' object.id %}" class="btn btn-dark">Edit Item</a>
          <a href="{% url 'food:delete-item' object.id %}" class="btn btn-danger">Delete Item</a>
        {% endif %}
       </div>
       </div>
    </div>

</div>
        
   {% else %}
        <h1>404</h1>
    {% endif %}

{% endblock %}

food/templates/food/edit_item.html
{% extends 'food/base.html' %}


{% block body %}
    <div class="container " style="height: 88vh; width: 100%;">
        <div class="row "style="height: 88vh; width: 100%; 
        display: flex;
        justify-content: center;
        ">
            <div class="" >
                <div class="card">
                    <div class="card-header bg-dark ">
                      <div class="card-title text-white">Edit Item</div>
                    </div>
                    <div class="card-body">
                        <form method="POST">

                        {% csrf_token %}
                        {%  for field in form %}
                           <div class="form-group" style="display: grid; grid-template-columns: 1fr 2fr;">
                            <label for="">{{field.name}}</label>
                            
                            {{field}}
                           </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-dark">Edit Item</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
 {% block body %}



       <div class="container">
        <div class="row d-block">

          {% for item in item_list%}
          <div class=" pt-4 d-flex gap-3 justify-content-between">
            
              <div class="col-md-4 flex-item d-flex  justify-content-end">
                  <img src={{item.item_image}} alt="" class="card" height="150px" width="150px">
               </div>
             <div class="col-md-4 flex-item">
               <h3>{{item.item_name}}</h3>
               <h5>{{item.item_desp}}</h5>
               <h6>${{item.item_price}}</h6>
               <h6>{{item.user_name}}</h6>


               
              </div>
                <div class="col-md-4 d-flex  align-items-center">
                   <a href="{%  url 'food:detail' item.id %}" class="btn btn-info p-4">View Details</a>
                </div>
              </div>

          
          {% endfor %}

       </div>
       
         
      

    
  



{% endblock %}
 

users/templates/user/login.html
{% extends 'food/base.html' %}


{% block body %}
    <div class="container " style="height: 88vh; width: 100%;">
        <div class="row "style="height: 88vh; width: 100%; 
        display: flex;
        justify-content: center;
      ">
            <div class="" >
                <div class="card">
                    <div class="card-header bg-info ">
                      <div class="card-title text-white">Login</div>
                    </div>
                    <div class="card-body">
                        <form method="POST">

                        {% csrf_token %}
                        {%  for field in form %}
                           <div class="form-group">
                            {{field.name}}
                            {{field}}
                           </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-info">Login</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/user/logout.html
<h1>You Have been logout</h1>

users/templates/user/profile.html
{% extends 'food/base.html' %}


{% block body %}
    <div class="container " style="height: 88vh; width: 100%;">
        <div class="row "style="height: 88vh; width: 100%; 
        display: flex;
        justify-content: center;
        ">
            <div class="" >
                <div class="card">
                    <div class="card-header bg-dark ">
                      <div class="card-title text-white">Profile</div>
                    </div>
                    <div class="card-body "  style="width:300px;">
                        <h1 style="text-align: center;">{{ user.username }}</h1>
                       <div class="card-item" style="
                       display: flex;
                       justify-content: center;">

                        <img src="{{ user.profile.image.url }}" width="100px" height="100px" style="border-radius: 50%;">

                       </div>
                        <h5 style="text-align: center;">{{ user.profile.location }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/user/register.html
{% extends 'food/base.html' %}


{% block body %}
    <div class="container " style="height: 88vh; width: 100%;">
        <div class="row "style="height: 88vh; width: 100%; 
        display: flex;
        justify-content: center;
        ">
            <div class="" >
                <div class="card">
                    <div class="card-header bg-info ">
                      <div class="card-title text-white">Register</div>
                    </div>
                    <div class="card-body">
                        <form method="POST">

                        {% csrf_token %}
                        {%  for field in form %}
                           <div class="form-group" style="display: grid; grid-template-columns: 1fr 2fr;">
                            <label for="">{{field.name}}</label>
                            
                            {{field}}
                           </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-info">Signup</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}